# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-01-31 04:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190131_0347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='user_like',
            new_name='users_like',
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 31, 4, 25, 10, 980836, tzinfo=utc)),
        ),
    ]
