# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-01 05:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20190131_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 5, 28, 25, 652130, tzinfo=utc)),
        ),
    ]
